### ISSUE TITLE
Rate limiting in shell scripts needed

### ISSUE THREAD

**Issue by leontebbens** [github/enable-security-alerts-sample#12]
There is a solution for #9, however the shell scripts in folder shell_script also lack rate limiting.
My solution is to add "sleep 1" after the PUT curl:
 `   curl -s -X PUT -H "Authorization: bearer $api_key" -H "Accept: application/vnd.github.london-preview+json" $enable_url`
`    sleep 1   #rate limiting to prevent blocking by github server`

In both shell scripts

**Comment by leontebbens** [comment]
I've made a pull request

**Comment by jhutchings1** [comment]
Thanks @leontebbens ✨ I reviewed and merged your PR.
