### ISSUE TITLE
Rate limiting needed

### ISSUE THREAD

**Issue by leontebbens** [github/enable-security-alerts-sample#9]
Hi, when using this script against our Github Enterprise Cloud I get rate limit errors:
"You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.
https://developer.github.com/v3/#abuse-rate-limits"

Suggestion: https://github.com/github/platform-samples/tree/master/api/ruby/find-inactive-members has rate limiting

**Comment by emtunc** [comment]
Was literally going to add an issue to this repo about this - rate limiting is needed for both security alerts + security fixes as they both trigger Github's anti-abuse controls.

**Comment by emtunc** [comment]
Thanks @jimmed - have tested and it works awesome!

@leontebbens take a look at the PR ^^

**Comment by leontebbens** [comment]
Thanx @jimmed - it solves the problem

**Comment by leontebbens** [comment]
please accept the pull request
